package com.schmoll.tlkw;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.schmoll.tlkw.swing.LoginPage;
import com.schmoll.tlkw.swing.MainForm;
import com.schmoll.tlkw.utils.ClsPropertySet;
import com.schmoll.tlkw.utils.StaticClass;
import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ApplicationContext;

import java.io.File;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@Slf4j
@MapperScan("com.schmoll.tlkw.mapper")
public class TlkwApplication {
    public static MainForm frame ;
    public static void main(String[] args) {
        ClsPropertySet webSetPro = new ClsPropertySet(System.getProperty("user.dir") + File.separator + "mesAgentConfig" + File.separator + "webSet.pro");
        ApplicationContext context = new SpringApplicationBuilder(TlkwApplication.class)
                .headless(false)
                .web(WebApplicationType.NONE)
                .run(args);
        StaticClass.setApplicationContext(context); // 调用上面的 setter
        //  核心改动：把 Spring 准备好的环境传给 StaticClass
        try {
            LoginPage loginPage = context.getBean(LoginPage.class);
            // 在单独的线程中启动Swing窗体
            java.awt.EventQueue.invokeLater(() -> {
                FlatDarculaLaf.setup();
                loginPage.showLoginFrame();
            });
        }catch (Exception e){
            log.error("Application====>{}",e.getMessage());
        }
    }

}
